### ISSUE TITLE
Incorrect Captcha code

### ISSUE THREAD

**Issue by victor994** [Mollom/MollomPHP#16]
We set up Mollom to check the form registrations and since last Month we have continuously experienced some issue with the captcha code sporadically. The users reported they have entered the correct captcha code as per image but it returns incorrect captcha code error thus asks users to try to submit another captcha code. Users will then get stuck in this process and never get through the captcha. Eventually they give up the registration and email us for help.

Since we only receive response from Mollom regarding the captcha match result, can we diagnose the problem in this case? Thank you for response.

**Comment by lkhaas** [comment]
Hi there - is the URL to your CAPTCHA form publically accessible?  If so, could you include it?  Also the public key (no need for private) for your Mollom account?  These can help the Mollom engineers troubleshoot what may be happening.  Thanks!

**Comment by victor994** [comment]
Hi Lisa,

Thanks for the reply. We have implemented Mollom throughout all the forms in our Events Calendar. And this issue has been experienced on multiple forms so I assume this is not related to specific forms.

I have created a test form at http://whatson.sydney.edu.au/events/published/captcha-not-working
The public key is b9709b85278a0ad07ad912efe2147114

Thanks for checking out.

**Comment by lkhaas** [comment]
Hi again - I just tried to put in a registration from the test URL you created and was successful.  Do you have a sessionId for a session where the CAPTCHA could not be solved?  We can inspect it that way as well.  Also - I see that you have a paid Mollom subscription.  You may wish to open an official support ticket here https://www.mollom.com/support/new as I'm going to be in and out of contact in the coming week but this way Acquia's support folks can keep up with this.

**Comment by victor994** [comment]
Sure, thanks for the response.
